/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/erfJ3LM3USh
 */
"use client";

import {
  CardTitle,
  CardDescription,
  CardHeader,
  CardContent,
  CardFooter,
  Card,
} from "../ui/card";
import { Label } from "../ui/label";
import { Input } from "../ui/input";
import { Checkbox } from "../ui/checkbox";
import { Button } from "../ui/button";
import Link from "next/link";
import { signIn } from "next-auth/react";
import { useState } from "react";
import { useRouter } from "next/navigation";

export default function Login() {
  const router = useRouter();
  const [register, setRegister] = useState({
    email: "",
    password: "",
  });
  const [error, setError] = useState("");
  const [pending, setPending] = useState(false);

  const handleChange = (e) => {
    const { name, value } = e.target;
    setRegister((prev) => ({ ...prev, [name]: value }));
  };

  const handleSubmit = async () => {
    if (!register.email || !register.password) {
      setError("Provide All the Cred");
    } else {
      setError("");
    }
    try {
      setPending(true);
      const res = await signIn("credentials", {
        email: register.email,
        password: register.password,
        redirect: false,
      });
      console.log(res);
      if (res.error) {
        setError("Invalid Credentials");
        setPending(false);
      }
      if (res.ok) {
        router.replace("/");
      }
    } catch (error) {
      setPending(false);
      console.log("Something Went Wrong");
    }
  };
  return (
    <div className="flex items-center min-h-screen px-4">
      <div className="mx-auto w-full max-w-sm space-y-4">
        <Card>
          {error ? (
            <div className="text-white bg-red-300 p-1 rounded text-center">
              {error}
            </div>
          ) : (
            ""
          )}
          <CardHeader className="space-y-2">
            <CardTitle className="text-3xl font-bold">Login</CardTitle>
            <CardDescription>
              Enter your email below to login to your account.
            </CardDescription>
          </CardHeader>
          <CardContent className="space-y-4">
            <div className="space-y-2">
              <Label htmlFor="email">Email</Label>
              <Input
                onChange={handleChange}
                id="email"
                placeholder="m@example.com"
                required
                type="email"
                name="email"
              />
            </div>
            <div className="space-y-2">
              <Label htmlFor="password">Password</Label>
              <Input
                onChange={handleChange}
                id="password"
                required
                type="password"
                name="password"
              />
            </div>
            <div className="flex items-center space-x-2">
              <Checkbox id="remember" />
              <Label className="leading-none" htmlFor="remember">
                Remember me
              </Label>
            </div>
          </CardContent>
          <CardFooter>
            <Button onClick={handleSubmit} type="submit" className="w-full">
              Sign in
            </Button>
          </CardFooter>
          <CardFooter>
            <Button
              onClick={() => signIn("google")}
              className="w-full"
              variant="outline"
            >
              Login with Google
            </Button>
          </CardFooter>
        </Card>
        <div className="flex items-center justify-between text-sm">
          <Link className="underline" href="#">
            Forgot your password?
          </Link>
          <Link className="underline" href="/register">
            Sign up for an account
          </Link>
        </div>
      </div>
    </div>
  );
}
