import { Inter } from "next/font/google";
import "../../styles/globals.css";
import SessionWrapper from "../components/SessionWrapper";
import { getServerSession } from "next-auth";
import NextAuth from "next-auth/next";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "E-commerce",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession();
  console.log(session);

  return (
    <SessionWrapper session={session}>
      <html lang="en">
        <body className={inter.className}>{children}</body>
      </html>
    </SessionWrapper>
  );
}
